baseurl = "https://azul.netlify.com"
languageCode = "pt-br"
title = "AZUL"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-123754589-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
	author = "Daniel Coutinho e Pedro Cavalcante"
	description = "Economia, Estatística, Programação "
	bio = "Estudantes de economia"

	twitter = ""
	facebook = ""

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"
  
  customJS = ["mathjax_support.html"]

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
twitterCardImage = ""
