baseURL = "https://azul.netlify.app/"
title = "AZUL"
copyright = "Copyright © 2008–2020, Pedro Cavalcante & Daniel Coutinho; all rights reserved."
paginate = 2
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = ""#"UA-123754589-1"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "Sobre"
    name = "Sobre"
    url = "/about/"
    weight = 0
	[[menu.main]]
    identifier = "Tags"
    name = "Tags"
    url = "/tags/"
    weight = 0
    [[menu.main]]
    identifier = "Categorias"
    name = "Categorias"
    url = "/categories/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Daniel Coutinho e Pedro Cavalcante"
  description = "Economia, Estatística, Programação"
  homepageImage = "/avatar.png"
  share = true
  showLanguageSwitcher = false


	enableRSS = true
	enableToc = true

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []


  [params.social]
    rss = true
      github = "https://github.com/danmrc/azul/tree/master/C%C3%B3digos"
    

  [params.prismJS]
    enable = false
    theme =  "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
  

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]