baseurl = "https://azul.netlify.com"
languageCode = "pt-br"
title = "AZUL"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-123754589-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
	author = "Daniel Coutinho e Pedro Cavalcante"
	description = "Economia, Estatística, Programação"
	bio = "Economia, Estatística, Programação"

	twitter = ""
	facebook = ""

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = ""

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
twitterCardImage = ""

  home = "Início"
	about = "Sobre"
	archive = "Arquivo"
	olderposts = "Antigos"
	
	enableShare = true
	tweet = ""
  share = ""
  
[social]

  github = "https://github.com/danmrc/azul/tree/master/C%C3%B3digos"