baseurl = "https://azul.netlify.com"
languageCode = "pt-br"
title = "AZUL"
theme = "minimo"
mathjax = true
googleAnalytics = "UA-123754589-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[frontmatter]
date = ["date","publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date","publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[[menu.main]]
  name = "Posts"
  url = "/post"
[[menu.main]]
    name = "Sobre"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "pt-br"

[params.info]
description = "Economia, Estatística, Programação"
title404 = "Nothing's here!"

[params.assets]
favicon = ""
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.comments]
enable = false

[params.comments.staticman.github]
username = ""
repository = ""
branch = ""

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"


[languages]
# edit this block for your own language
[languages.en]
lang = "pt-br"
languageName = "Português"
weight = 1

[params]
description = "A website built through Hugo and blogdown."

#highlightjsCDN = "//cdn.bootcss.com"    # options for highlight.js (version, additional languages, and theme)
#highlightjsVersion = "9.11.0"
#highlightjsLang = ["r", "yaml", "julia"]
#highlightjsTheme = "github"

#MathJaxCDN = "//cdn.bootcss.com"
#MathJaxVersion = "2.7.1"

[params.logo]
url = ""
width = 50
height = 50
alt = "Logo"

