---
title: "About"
date: "2018-07-18T21:48:51-07:00"
---

##Os Autores

Este blog é mantido por Daniel Coutinho e Pedro "Cava" Cavalcante. Escrevemos sobre economia, estatística e programação, frequentemente misturando os três - é "econometria" que chama?. Ambos usam o R, uma linguagem de programação voltada para estatística, e muitos dos posts são acompanhados do código. Replicabilidade e aprender-fazendo são a serventia da casa. Sem mais delongas, eis os dois autores:

**Daniel Coutinho** é formado em economia pela PUC-Rio (2018) e faz mestrado em economia na mesma instituição. É louco o suficiente para ter feito a monografia de fim de curso em econometria, e gosta de escrever sobre si próprio na terceira pessoa. Ele também é autor de um manual introduzindo o R, que você encontra [aqui](https://danmrc.github.io/R-para-Economistas/). 

**Pedro "Cava" Cavalcante** é graduando em Economia na UFF. É [associado do Instituto Mercado Popular](http://mercadopopular.org/author/cavalcante/) e trabalha no Setor de Mercado de Trabalho do IPEA-Rio. Gosta especialmente de economia da educação, estratégias de identificação interessantes e tem uma quedinha não-correspondida por matemática. Provavelmente é o último defensor de Stata no mundo, gosta de pão de queijo e nas horas vagas - além de escrever nesse blog e fazer memes de qualidade duvidosa - quebra a cabeça fazendo o pacote de R [economics101](https://github.com/pcavalcanteoliveira/economics101).


## Sobre o nome do blog

Traduza para o inglês... Se continuar não entendendo, vamos manter assim o mistério que é mais legal.
