---
title: Categorias
author: Pedro Cavalcante
date: '2021-06-22'
slug: categorias-uteis
categories:
  - Handwavy
images: []
authors: ["pedrocava"]
output:
  blogdown::html_page:
    pandoc_args: 
      [
      "--lua-filter=../script_number_and_braces.lua"
      ]
---

Hoje eu vi um tweet que me fez pensar. É gostoso pensar por escrito, sigam-me os desocupados.

# Uma turistada por Naturânia

Correndo o risco de alienar alguns leitores, imagine a terra mágica dos números naturais, Naturânia. Seus habitantes são... bem, os números naturais, eu espero que tenha ficado claro. Temos o Sr. Zero (eu disse que ia correr o risco de alienar alguns de vocês), a Sra. Quatrocentos e Setenta e Dois Mil, o googol, alguma potência de 10 menos sexy. 

Com altíssimo zoom, os habitantes desse país são todos **únicos**, não há um par de moradores de Naturânia tal que você, turista, consiga afirmar serem iguais. Nesse nível estamos fadados a ver floquinhos de neve tão únicos quanto dá para ser. 

No entanto podemos dar um pouco de _zoom out_ e ver que sim existem grupos de moradores mais similares do que outros. Afinal, podemos agrupar cidadãos que, a rigor são diferentes, em grupos que compartilham certas propriedades. Essas propriedades que usamos como critério de pertencimento a um certo grupo são escolhas arbitrárias. Por exemplo:

*Definição:* Um habitante de Naturânia $n$ é dito *estrambólico* se terminar em 1, 2, 3 ou 5. Um habitante que termina em 4, 6, 7, 8 ou 9 é dito *feão* e um número que termina em 0 é dito *isentão*.

Em princípio nada torna essas propriedades que eu defini menos válidas do que as que te ensinaram na escola. Um número pode ser estrambólico e primo como 1, 2 e 3 ou estrambólico e composto, 12. Um número pode ser feão e par, como 44. Ou par e isentão, como 10. 13 é estrambólico e Fibonacci.

Até existem algumas relações essas propriedades com as clássicas:

*Proposição:* Todo número isentão é par.

*Demonstração:* Putz foi mal fica para o leitor, essa eu me recuso a fazer.

Definir categorias é uma empreitada com boas doses de arbitrariedade. Te convenci disso? Se não, recomendo parar aqui porque só vai piorar. Se sim, vamos prosseguir.

# Nem todo recorte é útil

Dito isso, arbitrariedade não é ruim, é o arroz com feijão de uma boa teoria. O "mundo real", seja lá o que for, é uma massa amorfa de eventos em níveis diferentes: elétrons orbitam átomos que compõem proteínas de células que fazem parte de um indivíduo, membro de uma sociedade que interage (via troca cultural, comércio, guerra ou organismos multilaterais) com outras sociedades. 

O que nós fazemos é traçar linhas, ignorar detalhes que não parecem os mais relevantes e atacamos um problema. Dados esses passos iniciais podemos relaxar hipóteses para criar uma visão mais panôramica dos mecanismos por trás de racismo, metástase, transferência de calor, integrabilidade e depressão. 

"Traçar linhas" é onde a magia acontece. Espero, leitor, que você veja que qualquer Teoria dos Números fundada em recortes como números estrambólicos, feões e isentões não deve ir muito longe. O que *não* quer dizer que essa Teoria Estrambólica de Números tem algo de *errado*. 

Nenhum ataque bem-sucedido a esse minúsculo edifício teórico que construí nesta página deve afirmar que ele está "errado" porque, atenção, *definições são arbitrárias*. Proposições como "se $a$ e $b$ são feões então $a + b$ é primo" são claramente falsas, afirmações erradas, mas as definições usadas continuam sendo o que são.

Algumas definições, ainda que inteiramente arbitrárias, são úteis: números primos, quadrados perfeitos, números pares e ímpares. Um sinal de que são recortes úteis e informativos dos habitantes de Naturânia é que embora totalmente desconectados uns dos outros (suas definições são independentes), interagem. Todo número primo ímpar é a soma de dois quadrados perfeitos - ler isso pela primeira vez deveria te causar profundo desconforto porque números primos, ímpares e quadrados perfeitos, nas suas definições, não têm relação alguma. 

Espero ter te convencido que duas teorias podem competir como explicadoras do mesmo fenômeno, nenhuma estar *errada* e ainda assim, uma ser claramente superior. Podemos debater como definir essa "superioridade" depois, agora precisamos apenas supor que é possível. Se, mesmo que apenas um pouco, *não* houve convencimento ou se você enganchar nessa possibilidade de uma teoria "superior" em algum sentido, eu de novo aviso que só vai piorar.

# Instituirânia

Imagine um plano, um tecido enorme. Vamos escolher duas características que sociedades podem ter, associar um eixo a cada uma e posicionar cada sociedade neste plano. Vamos simular alguns cenários e escolher características.

Sociedades em que a maioria achava que o [vestido que quebrou a internet](https://en.wikipedia.org/wiki/The_dress) era roxo ficam mais ao norte, as que viram dourado mais ao sul. Sociedades em que filhos saem da casa dos pais, na média, depois dos 30 anos ficam mais ao leste, onde é antes dos 30, ao oeste. Não é difícil ver que a proximidade de quaisquer duas sociedades, nesse cenário, provavelmente nada tem a ver com a sua similaridade em termos de desigualdade ou renda média. Categorizar sociedades com esses critérios equivale a um primo pobre da Teoria Estrambólica dos Números.

Vamos reorganizar essa configuração. No eixo horizontal agora posicionamos sociedades de acordo com a segurança de direitos de propriedade e no vertical quanto ao risco envolvido em ser uma minoria (e.g. algumas sociedades têm perseguição política a opositores, outras não, algumas proíbem homossexualidade, outras abertamente reconhecem casamentos homoafetivos). 

Algo mudou e agora sociedades mais prósperas (mais ricas e menos desiguais) se acumulam em uma certa região, ainda que existam sociedades razoavelmente ricas espalhadas aqui e ali, em particular estados que podem se financiar com rendas de recursos naturais. Duas características que são ortogonais agora parecem ter uma viva interação. E se essas não forem as únicas características interessantes?

Nossa história bidimensional quebra aqui. Vamos adicionar dimensões e com isso criamos um mapa, multidimensional, de institucionalidade. Com zoom o suficiente são todas indiscutivelmente únicas, como os habitantes de Numerânia. Dando dois passos para trás e fazendo definições arbitrárias-porém-espertas vemos padrões emergirem.

Sociedades com fortes direitos de propriedade em geral são mais ricas. Sociedades em que minorias não são reféns de perseguição e/ou pagam menos aluguéis às maiorias também tendem a ser sociedades mais prósperas. Esses recortes dizem respeito a algumas características da institucionalidade, do conjunto de regras formais e informais, de cada sociedade. 

E existem outros, ah tantos outros. Como é regulada a infraestrutura de transportes? São _alguns eixos_ a mais só nesse assunto. E a legislação em torno de licensiamento ambiental? O que um cidadão precisa para declarar impostos? Executar um contrato é simples ou um pesadelo burocrático interminável? O governo rotineiramente assassina inocentes? Se um general ligado ao presidente acorda querendo quebrar as regras impostas pela vida militar ele faz isso sem consequências? E um empresário médio, ele tem mais a ganhar contratando engenheiros, comprando maquinário e investindo ou é mais rápido e fácil ir para Brasília? 

Qualquer regime político que seja resumido em algum "ismo" equivale a algum subconjunto deste "espaço institucional". A práxis de um programa político é a _tentativa_ de deslocar uma sociedade de um vetor neste espaço para outro que corresponde às características institucionais desejadas. A aprovação de uma série de reformas no governo Temer deslocou o Brasil em alguns eixos, o governo atual está fazendo o que pode para deslocar em outros.

Alguns eixos são altamente informativos, direitos de propriedade por exemplo. Outros nem tanto, como por exemplo se é o estado ou a iniciativa privada que pratica certas atividades econômicas. No gradiente economia de mercado - economias planejadas existe um pouco de tudo. Economias de mercado pobres, economias de mercado prósperas, economias de mercado com baixa e com alta desigualdade, economias planejadas pobres e economias (ex-)planejadas nem tão pobres assim. 

Espero ter te convencido que qualquer teoria social envolve uma escolha de recortes a serem feitos e assim como alguns recortes são mais úteis que outros em Teoria dos Números, aqui isso também acontece. Algumas interações entre recortes independentes são altamente consistentes, outras menos.

E afinal, por que vim parar aqui? Bem, o tweet de mais cedo era [esse aqui](https://twitter.com/demori/status/1407151605263343618). Demori é um jornalista realizado, um profissional. O motivo de um pedaço tão grande da intelectualidade ter esse tipo de crença firmemente pautada em recortes obtusos me escapa. 

Para quem só tem um martelo tudo é um prego, certo? Se o seu repertório de categorias para descrever equilíbrios políticos se resume a capitalismo e dois ou três ismos competidores, as suas crenças e preferências políticas provavelmente vão ser tão obtusas quanto. O que não é advogar pela coleta enciclopédica de "ismos". 

O ponto aqui não é uma competição por quem consegue enumerar mais ideologias políticas de nicho, é de reconhecer que nossos prismas para fazer sentido do mundo são desserviços se livres de desconfiança. Digo mais. 

Pão de alta dimensionalidade é quase todo casca. O melhor chute, e a estatística está a meu favor nessa, é que as suas categorias estão mais para Teoria Estrambólica de Números do que Geometria Diferencial. No espaço amostral de recortes e categorias de mundo, os de baixa informação são, **de longe** os mais comuns. 