---
title: "Sobre o Blog"
date: "2018-07-18T21:48:51-07:00"
---

Este blog é mantido por Daniel Coutinho e Pedro "Cava" Cavalcante. Escrevemos sobre economia, estatística e programação, frequentemente misturando os três. A ideia é escrever de maneira replicável e acessível (na medida do possível) sobre assuntos que gostaríamos de ter visto de outra forma, que estamos estudando ou o que tenham nos chamado a atenção. Acreditamos em aprender fazendo.

## Os Autores

**Daniel Coutinho** é formado em economia pela PUC-Rio (2018) e faz mestrado em economia na mesma instituição. É louco o suficiente para ter feito a monografia de fim de curso em econometria, e gosta de escrever sobre si próprio na terceira pessoa. Ele também é autor de um manual introduzindo o R, que você encontra [aqui](https://danmrc.github.io/R-para-Economistas/). 

**Pedro "Cava" Cavalcante** é formado em Economia pela Universidade Federal Fluminense (2020), é Head de Dados na [Cumbuca](www.appcumbuca.com). Gosta  de estratégias de identificação espertas, filosofia da mente, teoria musical e tem uma quedinha ~~não-correspondida~~ por matemática. 

## Sobre o nome do blog

Traduza para o inglês... Se continuar não entendendo, sorte sua.
