---
title: print("Hello,world!")
author: Daniel Coutinho e Pedro Cavalcante
date: '2018-07-18'
slug: print-hello-world
categories:
  - Geral
tags:
  - Apresentação
authors: []
---

Este é o primeiro post do AZUL, um blog mantido por Daniel Coutinho e Pedro "Cava" Cavalcante. Sem mais delongas, eis os dois autores:

**Daniel Coutinho** é formado em economia pela PUC-Rio (2018) e faz mestrado em economia na mesma instituição. É louco o suficiente para ter feito a monografia de fim de curso em econometria, e gosta de escrever sobre si próprio na terceira pessoa.

**Pedro "Cava" Cavalcante** é graduando em economia na UFF e estagiário de pesquisa no IPEA. Gosta especialmente de economia da educação, estratégias identificação interessantes e tem uma quedinha não-correspondida por matemática. Provavelmente é o último defensor de Stata no mundo. 

Nós vamos escrever sobre economia, programação e estatística - recentemente renomeada de ciência dos dados - frequentemente misturando os três. Eventuais desvios pela matemática ocorrerão, já que as três áreas tem como base a matemática. Não sabemos o que o caminho a frente nos reserva. Esperamos que vocês aproveitem o que escrevemos.