---
title: 'Ah, mas o Golpe...'
author: 'Pedro Cavalcante'
date: '2023-01-24'
slug: first-class-deliverables
categories:
  - Handwavy
tags:
  - Política
  - Handwavy
images: []
authors: ["pedrocava"]
output:
  blogdown::html_page:
    pandoc_args: 
      [
      "--lua-filter=../script_number_and_braces.lua"
      ]
---

# Alô, quem fala?

> Em que eu falo no que consiste esse exercício mental. 

Aqui quem fala é da Terra, pra variar estamos em guerra, etc etc. Sou bem consciente de que ao escrever o que estou escrevendo, crio uma associação estética com gente que eu... como falar isso educadamente... abomino... Acho que ter alinhamento de pautas com coalizões com as quais você não se vê muito alinhado é uma inevitabilidade - e já fiz as pazes com isso. 

Dá para ir do Rio a São Paulo de várias maneiras, algumas mais razoáveis que outras. Primeiro eu queria delimitar o que *não* estou pensando. Temer não é um *cool guy*. Eu não acho justificado o carinho não-apologético por ele que a libsfera nacional tem. Não acho que exista reforma ou política (com "sucesso" ou não) que apague o conteúdo dos áudios do Joesley.

Eu me entendo estar no Campo Progressista. Quem eu acredito se encaixar nele comigo é mais ou menos quem quer que se veja no Campo Progressista. Aceito todo o relevo filosófico e de práxis política que isso implica. O que eu *tento* fazer a seguir é (i) expor uma leitura de boa-fé de um ponto do qual eu discordo, (ii) explicar por que eu acho que ele não procede e talvez (iii) um leve exercício de empatia democrática.

# Relaxamento Semântico

> Em que eu falo um pouco sobre como brincar de semântica é ok I guess, mas nem tanto - SEM CITAR novilíngua




# Racionalidade

> Em que eu elaboro por que é _do interesse de uma coalizão de agentes_ emplacar a leitura do golpe e que aceitar isso acriticamente é preguiçoso




