---
title: Como receber atualizações do blog no celular
author: Daniel Coutinho
date: '2018-12-03'
slug: como-receber-atualizações-do-blog-no-celular
categories:
  - Meta
tags:
  - Telegram
authors: ["danielc"]
---

(TL;DR: você pode receber os posts novos do azul no seu celular, veja a lista no fim dois parágrafos abaixo)

Nós passamos algum tempo pensando em como melhorar a distribuição de posts para os nossos leitores. Afinal, é extremamente ineficiente abrir o blog na esperança de ver um novo post e.. nada novo. Economistas sempre criticam ineficiências, e nós não poderíamos ser exceção. 

Por isso, criamos um bot no Telegram (o concorrente do Whatsapp) que te avisa automaticamente quando sai um post novo no blog. Aqui está o passo a passo:

* Baixe (ou use direto na web) o [Telegram](https://telegram.org/) e faça sua conta
* Na busca do app, busque pelo nosso bot, @azulblogbot
* Digite /start
* Digite /getupdate para obter novas atualizações

Você deve receber uma mensagem confirmando a sua inscrição, mas isso pode demorar um pouco.

Futuramente eu escreverei no blog como eu fiz o bot e as rotinas (dentro do próprio R) que permitem com que a gente divulgue o blog dessa maneira.

Eu sei que muitos vocês vão se perguntar "Por que não fazer uma página no face, afinal..." mas o problema é que:

1. Nós não temos tanto tempo pra ficar criando os posts no braço. O ideal seria automatizar - como fizemos com o Telegram. Para isso precisariamos de um app do Face...

2. Mas criar um app no face que tenha poderes de fazer posts públicos é um pesadelo burocrátrico, graças ao escândalo da Cambrigde Analytica. O app tem que ser enviado para review pelo facebook, com o cnpj da empresa responsável... Muito trabalho para um hobby de dois universitários.

Esperamos que vocês se inscrevam!