---
title: 'Sistemas dinâmicos II: Expectativas racionais'
author: Daniel Coutinho
date: '2020-01-02'
slug: sistemas-dinâmicos-ii
categories:
  - Matemática
  - Macroeconomia
tags:
  - Sistemas Dinâmicos
  - Blanchard Khan
  - Álgebra Linear
draft: true
---

Há muito tempo atrás eu escrevi sobre [Álgebra Linear e sistemas dinâmicos](https://azul.netlify.com/2018/11/06/sistemas-dinamicos-e-algebra-linear/). Lá, eu falava de um caso em que o sistema era $x_t = Ax_{t-1}$, onde $x_t$ era um vetor e $A$ tinha que ter autovalores menores que 1 em módulo para garantir a estabilidade do sistema. Apesar de ser um caso bem interessante, muitas vezes em economia nós temos que lidar com _expectativas_ e assumimos expectativas racionais - que pode ser definida de várias maneiras, mas a mais intuitiva é pensar que agentes não cometem erros sistematicamente. Um caso "famoso" de expectativas racionais é a curva de Phillips novo keynesiana:

$$\pi_t = \beta E_t \pi_{t+1} + \kappa \tilde{y}_t$$

Onde $\pi$ é a inflação e $\tilde{y}_t$ é o hiato do produto. 

Eu me perguntei durante muito tempo "como diabos você se livra dessa expectância?". Com expectativas adaptativas, a resposta é bem simples: $E_t(\pi_{t+1}) = \pi_t$. Para entender como funciona, vamos dar um passo para trás. 

Suponha que você tem uma única equação, linear, $x_t = \alpha x_{t-1}$. Podemos sempre iterar para trás e realizar substituição recursiva:

$$
x_t = \alpha x_{t-1}\\
x_{t-1} = \alpha{}x_{t-2}\\
x_{t-2} = \alpha x_{t-3}\\
...$$

E substitua a última na penúltima, ..., a terceira na segunda e a segunda na primeira para obter:

$$x_t = \alpha^tx_0$$

Onde $x_0$ é uma condição inicial. Veja que se $|\alpha| > 1$, o sistema explode. Caso contrário, o processo colapse parazero. Normalmente, em economia, nós imaginamos que existe um choque aleatória $\varepsilon_t$ e o sistema é $x_t = \alpha x_{t-1} + \varepsilon_t$. Isso é só um AR(1) usual e a representação recursiva funciona da mesma forma, mas agora com um termo extra:

$$x_t = \alpha^t x_0 + \sum_{j=0}^t \alpha^j \varepsilon_{t-j}$$

Até aqui, nada de extremamente novo: esse é o ferramental usual de equações em diferenças. Agora, considere que nós temos uma única equação que tem uma expectativa (que assumimos ser racional):

$$E_t(y_{t+1}) = \lambda y_t$$

Veja que se $y_t = y_{t+1} = 0$, a equação está no "estado estacionário". 

O truque aqui é ao invés de iterar para trás, nós iteramos para frente:

$$
E_t(y_{t+1}) = \lambda y_t\\
E_t(y_{t+2}) = \lambda y_{t+1}\\
...
$$



Agora, assuma que no $\lim_{j \rightarrow \infty}E_t(y_{t+j}) = 0$ ou seja, todo mundo espera que o sistema vai voltar ao equilíbrio. 
E agora $s_t$ é uma variável aleatória ou determinística. Note que se $y_{t+1} = y_t = 0$ e $s_t = 0$ também, a equação está no "estado estacionário"